server:
  port: 8085
spring:
  datasource:
    password: root
    url: jdbc:postgresql://localhost/Shahab
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
