spring:
  application:
    name: WebFluxDemo
    
  r2dbc:
    url: r2dbc:h2:mem:///testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

