server:
  port: 4444
spring:
  datasource:
    password: postgre
    url: jdbc:postgresql://localhost/entityrelationship
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher